# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170611_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='Ppost',
        ),
    ]
