# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170611_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer', models.BooleanField(default=True)),
                ('Ppost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
            ],
        ),
    ]
